# Taskfile для автоматизации команд разработки
# See: https://taskfile.dev/api/
version: "3"

tasks:
  default: # Дефолтная задача (выполняется при запуске без аргументов)
    cmds:
      - task: generate
  
  generate: ## Команда для генерации
    aliases: ## Алиасы команды
        - gen
    desc: "Generate code from proto files"
    cmds: 
      - |
        protoc -I proto proto/sso/sso.proto \ # Исходный proto файл
          --go_out=./gen/go/ \                # Выход для Go кода
          --go_opt=paths=source_relative \    # Относительные пути
          --go-grpc_out=./gen/go/ \           # Выход для gRPC кода
          --go-grpc_opt=paths=source_relative # Относительные пути для gRPC
